spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notescape_db
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mvc:
    log-request-details: true
    pathmatch:
      matching-strategy: ant_path_matcher

  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8087
        username: root
        password: root123
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
          service-base-url: http://localhost:8080
  security:
    user:
      name: adm
      password: zxf
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: TRACE
    com.nebula.notescape.security: TRACE
    com.nebula.notescape.service: TRACE
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

jwt:
  secret: e0a6712b94dfcc2908c31c82f380465d57edd480455caa10d14632c225f6dd33
  expiration: 604800000