spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/notescapedb
    username: root
    password: fegah127
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect

  mvc:
    log-request-details: true
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    web: TRACE
    com.example.notescapetryingstill.service: TRACE


jwt:
  secret: e0a6712b94dfcc2908c31c82f380465d57edd480455caa10d14632c225f6dd33
  expiration: 604800000
