spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notescape_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mvc:
    log-request-details: true
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    web: TRACE
    com.nebula.notescape.security: TRACE
    com.nebula.notescape.service: TRACE
#  file:
#    name: notescape.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
